---
ceph: false
ceph_ansible: false
cephadm: false
ceph_managed: false
ironic: false
ironic_automated_cleaning: true
kayobe_manages_physical_network: true
wazuh: false
wazuh_managed: false
wazuh_ansible: false
